export const types: string[] = [
  " فروع كورال",
  "كولكشن رجالي",
  "اكسسوارات",
  "أحذية",
  "كولكشن الشتاء",
  "كولكشن الصيف",
];
export const person: any[] = [
  {
    title: "الاطفال",
    brief: "للبنات بعمر 1-10 سنوات",
    image: "/images/girlKid.jpg",
  },
  {
    title: "الاطفال",
    brief: "للأولاد بعمر 1-10 سنوات",
    image: "/images/boyKid.jpg",
  },
  {
    title: "النساء",
    brief: "الفساتين",
    image: "/images/women1.jpg",
  },
  {
    title: "النساء",
    brief: "القمصان والبلوزات",
    image: "/images/women2.jpg",
  },
  {
    title: "النساء",
    brief: "الهوديز والكنزات الثقيلة",
    image: "/images/women3.jpg",
  },
  {
    title: "النساء",
    brief: "وصل حديثا",
    image: "/images/women4.jpg",
  },
  {
    title: "الرجال",
    brief: "التي-شيرتات والسترات",
    image: "/images/men1.jpg",
  },
  {
    title: "الرجال",
    brief: "وصل حديثا",
    image: "/images/men2.jpg",
  },
];
export const clothes: string[] = [
  "/images/trend1.jpg",
  "/images/trend2.jpg",
  "/images/trend3.jpg",
  "/images/trend4.jpg",
];
export const cards: string[] = [
  "/images/card.png",
  "/images/card (1).png",
  "/images/card (2).png",
  "/images/card (3).png",
  "/images/card (4).png",
  "/images/card (5).png",
];
export const filters: any[] = [
  {
    title: "ترتيب حسب",
    subTitle: [
      "جديد في المتجر",
      "من الاعلي سعرا للاقل سعرا",
      "من الاعلي سعرا للاقل سعرا",
    ],
  },
  {
    title: "المقاس",
    subTitle: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
  },
  {
    title: "الالوان",
    subTitle: [
      "أسود",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
      "بيج",
      "أبيض",
      "أزرق",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
    ],
  },
  {
    title: "الالوان",
    subTitle: [
      "أسود",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
      "بيج",
      "أبيض",
      "أزرق",
      "مختلط",
      "بيج",
      "أبيض",
      "أزرق",
    ],
  },
  {
    title: "نوع المنتج",
    subTitle: [
      "فستان",
      "تيشرت",
      "شورت",
      "بنطال",
      "حذاء",
      "قميص",
      "جاكيت",
      "تيشرت بولو",
    ],
  },
];
